#!/bin/bash

mysql=$(dpkg-query -W -f='${status}' mysql 2>/dev/null | grep -c "MySQL on juba installeeritud")
if [ $mysql -eq 0 ]
then
	echo "Installeerimine..."
	apt-get install mysql-server -y

elif [ $mysql -eq 1 ]
then
	echo "MySQL on installitud"
	systemctl status mysql
fi
