#!/bin/bash

mysql=$(dpkg-query -W -f='${status}' mysql 2>/dev/null | grep -c "MySQL on juba installeeritud!")
if [ $mysql -eq 0 ]
then
	echo "MySQL-i installeerimine..."
	apt-get install -y mysql-server

elif [ $mysql -eq 1 ]
then
	echo "MySQL on installeeritud!"
	systemctl status mysql
fi
